en/urls.py
from django.urls import re_path
from en.views import IndexView, BlogListView, BlogDetailView

urlpatterns = [
    re_path(r'^$', IndexView.as_view()),  
    re_path(r'^blog/$', BlogListView.as_view()),
    re_path(r'^blog/(?P<slug>[\w\-]+)/$', BlogDetailView.as_view()),
] 

home/urls.py
from django.conf.urls import include
from django.urls import re_path
from home.views import IndexView

urlpatterns = [
    re_path(r'^$', IndexView.as_view())
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path, re_path




urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('home.urls')),
    re_path(r'^en/', include('en.urls')),
    re_path(r'^pt-br/', include('ptbr.urls')),
]

# Comment out these lines for production
from mysite.settings import dev
from django.conf.urls import handler404, handler500
from mysite.views import Error400, Error403, Error404, Error500
from django.views.static import serve

handler400 = Error400.as_view()
handler403 = Error403.as_view()
handler404 = Error404.as_view()
handler500 = Error500.as_view()

if dev.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': dev.MEDIA_ROOT,
        }),
    ] 

ptbr/urls.py
from django.urls import re_path
from ptbr.views import IndexView, BlogListView, BlogDetailView

urlpatterns = [
    re_path(r'^$', IndexView.as_view()),  
    re_path(r'^blog/$', BlogListView.as_view()),
    re_path(r'^blog/(?P<slug>[\w\-]+)/$', BlogDetailView.as_view()),
] 

en/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save
from home.utils import unique_slug_generator




class TopicModel(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'topics'



class PostModel(models.Model):
    topic = models.ForeignKey(TopicModel, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=140)
    slug = models.SlugField(max_length=142, unique=True)
    body = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='blog', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'posts'
        


class MuseumModel(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='blog', null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='artworks'
        get_latest_by = ['date']


def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance, instance.title, instance.slug)
    
pre_save.connect(slug_save, sender=PostModel)

home/models.py
from django.db import models

# Create your models here.

ptbr/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import pre_save
from home.utils import unique_slug_generator




class TopicModel(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'topics'



class PostModel(models.Model):
    topic = models.ForeignKey(TopicModel, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=140)
    slug = models.SlugField(max_length=142, unique=True)
    body = models.TextField()
    date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='blog', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'posts'
        


class MuseumModel(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='blog', null=True, blank=True)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural='artworks'
        get_latest_by = ['date']



def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance, instance.title, instance.slug)
    
pre_save.connect(slug_save, sender=PostModel)

en/views.py
from django.conf import settings
from django.views.generic import TemplateView, ListView, DetailView
from en.models import MuseumModel, PostModel, TopicModel
from django.db.utils import OperationalError


class IndexView(TemplateView):
    template_name = 'enindex/index.html'



class BlogListView(ListView):
    template_name = 'enblog/newsfeed.html'
    model = PostModel
    queryset = PostModel.objects.order_by('-date')[:25]
    try: 
        artwork = MuseumModel.objects.latest('date')
    except OperationalError:
        pass
    except MuseumModel.DoesNotExist:
        pass
    topics = TopicModel.objects.all()

    def get_context_data(self, **kwargs):
        kwargs['post_list'] = self.queryset
        try:
            kwargs['artwork'] = self.artwork
        except AttributeError:
            pass
        kwargs['topic_list'] = self.topics
        return super(BlogListView, self).get_context_data(**kwargs)




class BlogDetailView(DetailView):
    template_name = 'enblog/post.html'
    model = PostModel

home/views.py
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name = 'home/index.html'

mysite/views.py
from django.views.generic import TemplateView
from django.shortcuts import render



class Error400(TemplateView):
    template_name = '400.html'

    def get(self, request):
        return render(request, self.template_name, status=400)



class Error403(TemplateView):
    template_name = '403.html'

    def get(self, request):
        return render(request, self.template_name, status=403)



class Error404(TemplateView):
    template_name = '404.html'

    def get(self, request):
        return render(request, self.template_name, status=404)



class Error500(TemplateView):
    template_name = '500.html'

    def get(self, request):
        return render(request, self.template_name, status=500)

ptbr/views.py
from django.conf import settings
from django.views.generic import TemplateView, ListView, DetailView
from ptbr.models import MuseumModel, PostModel, TopicModel
from django.db.utils import OperationalError



class IndexView(TemplateView):
    template_name = 'ptbrindex/index.html'



class BlogListView(ListView):
    template_name = 'ptbrblog/newsfeed.html'
    model = PostModel
    queryset = PostModel.objects.order_by('-date')[:25]
    try: 
        artwork = MuseumModel.objects.latest('date')
    except OperationalError:
        pass
    except MuseumModel.DoesNotExist:
        pass
    topics = TopicModel.objects.all()

    def get_context_data(self, **kwargs):
        kwargs['post_list'] = self.queryset
        try:
            kwargs['artwork'] = self.artwork
        except AttributeError:
            pass
        kwargs['topic_list'] = self.topics
        return super(BlogListView, self).get_context_data(**kwargs)



class BlogDetailView(DetailView):
    template_name = 'ptbrblog/post.html'
    model = PostModel

en/templates/enblog/newsfeed.html
<!DOCTYPE html>
<html lang='eng'>
<head>
    {% load static %}
    <title> Alleyways | Marcelo Cardoso </title>
    <meta charset='utf8'/>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='shortcut icon' type='image/png' href='/static/home/img/m.jpg' sizes='32x32'/>
    <link rel='stylesheet' type='text/css' href="{% static 'blog/css/main.css'%}"/>
    <script src='https://code.jquery.com/jquery-3.3.1.min.js' integrity='sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=' crossorigin='anonymous'></script>
    <script id="dsq-count-scr" src="//marcelo-page.disqus.com/count.js" async></script>
    <script src="{% static 'blog/js/newsFeedEn.js' %}"></script>
    {% include "universal/google.html" %}
    <script>
        {% for topic in topic_list %}
        $(document).ready(function() {
            $('#publication-container-{{topic.name}}').click(function() {
                var publicationContained = $('#publication-contained-{{topic.name}}');
                if (publicationContained.css('display') == 'block') {
                    $.fn.closePublicationContained(publicationContained);
                    if (publicationContained.next().is('li')) {
                        setTimeout(function() {
                            publicationContained.next().animate({
                                'margin-top': '0'
                                });
                        }, 200);
                    }
                    else {

                    }
                } else if (publicationContained.css('display') == 'none') {
                    $.fn.openPublicationContained(publicationContained);
                    if (publicationContained.next().is('li')) {
                      publicationContained.next().animate({
                        'margin-top': publicationContained.outerHeight() + 30
                        });
                    }
                    else {

                    }
                } else {
                    
                }
            });
        });
        {% endfor %}
    </script>
</head>

<body id='top'>    
    <div id='toggle-sidebar-wrapper'>
        <div id='toggle-wrapper'>
            <div id='toggle-container'>
                <a class='button' id='toggle-button' aria-hidden='true'>+</a>
            </div>
        </div>
        <div id='sidebar-wrapper'>
            <ul>
                <div id='remote-controller-wrapper'>
                    <li>
                        <a class='close-sidebar-button button' id='index-button'>m</a>
                        <a class='close-sidebar-button button'>-</a>
                        <a href='#top' class='close-sidebar-button button scroll'>top</a>
                    </li>
                </div>
                {% for topic in topic_list %}
                <li class='publication-container' id='publication-container-{{topic.name}}'><a class='button topic-name'>{{topic.name}}</a></li>
                    <div class='publication-contained' id='publication-contained-{{topic.name}}' style='position: asbsolute;
                                                                                                        background-color: #fff;
                                                                                                        box-shadow: -2px 2px 4px 2px #9b9b9b71 !important;
                                                                                                        display: none;
                                                                                                        margin-top: 10px;
                                                                                                        margin-left: 25px;
                                                                                                        margin-bottom: 20px;'>
                    {% for post in topic.postmodel_set.all %}
                    <li><a href='#{{post.id}}' class='close-sidebar-button-post scroll' class='post-title'>{{post.title}}</a></li>
                    {% endfor %}
                </div>
                {% endfor %}
            </ul>
        </div>
    </div>
    <header>
        <div id='blog-title-wrapper'>
            <h1 id='blog-title'>Alleyways</h1>
        </div>
    </header>
    
    <div id='essay-wrapper'>
        <div class='mona-lisa'>
            <img src = "{{ artwork.image.url }}" title='{{ artwork.title }}'>
        </div>
        {% for post in post_list %}
        <div class='essay-header'>
            <h2 class='essay-title'><a href='/en/blog/{{post.slug}}' name='published-essay' id='{{post.id}}'>{{post.title}}</a></h2>
            <div class='essay-date'>
                {{ post.date|date:"M d, Y" }}
                <div class ='disqus-comment-count' data-disqus-identifier='{{post.id}}'>
                </div>
            </div>
        </div>
        <div class='essay'>{{ post.body|safe|linebreaks }}</div>
        <div class='mona-lisa'>
            {% if post.image.url != None %}
            <a><img src="{{ post.image.url }}"></a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</body>
</html>

en/templates/enblog/post.html
<!DOCTYPE html>
<html lang='eng'>
<head>
    {% load static %}
    <title> {{object.title}} | Marcelo Cardoso </title>
    <meta charset='utf8'/>
	<meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' href="{% static 'blog/css/main_post.css'%}"/>
    <link rel='shortcut icon' type='image/png' href='/static/home/img/m.jpg' sizes='32x32'/>
    <script src='https://code.jquery.com/jquery-3.3.1.min.js' integrity='sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=' crossorigin='anonymous'></script>
    <script id="dsq-count-scr" src="//marcelo-page.disqus.com/count.js" async></script>
    <script src="{% static 'blog/js/post.js' %}"></script>
    {% include "universal/google.html" %}
</head>

<body id='top'>    
    <div id='toggle-sidebar-wrapper'>
        <div id='toggle-wrapper'>
            <div id='toggle-container'>
                <a class='button' id='blog-button' aria-hidden='true'><</a>
            </div>
        </div>
    </div>

    <div id='essay-wrapper'>
        <div id='essay-header'>
            <h2 class='essay-title'><a name='published-essay' id='{{object.id}}'>{{object.title}}</a></h2>
            <div class='essay-date'>
                {{ object.date|date:"M d, Y" }}
            </div>
        </div>
        <div class='essay'>{{ object.body|safe|linebreaks }}</div>
        <div class='mona-lisa'>
        {% if object.image.url != None %}
            <a><img src="{{ object.image.url }}"></a>
        {% endif %}
        </div>
        <div id='disqus_thread'></div>
        <script src="{% static 'blog/js/disqusEn.js' %}"></script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </div>
</body>
</html>

en/templates/enindex/index.html
<!DOCTYPE html>
<html lang='eng'>
<head>
	{% load static %}
    <title> Marcelo Cardoso </title>
    <meta charset="utf8" />
    <meta name="viewport" content="width = device-width, initial-scale = 1">
	<link rel='shortcut icon' type='image/png' href='/static/home/img/m.jpg' sizes='32x32'/>
	<link rel='stylesheet' href="{% static 'index/css/main.css' %}" type='text/css'/>
	<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.4.1/css/all.css' integrity='sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz' crossorigin='anonymous'>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/97/three.js'></script>
	<script src='https://code.jquery.com/jquery-3.3.1.min.js' integrity='sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=' crossorigin='anonymous'></script>
	<script src="{% static 'index/js/index.js' %}"></script>
	<script src="{% static 'index/js/indexEn.js' %}"></script>
	{% include "universal/google.html" %}
</head>
<body>
	<div id='wrapper'>
		<header>
			<div id='menu'>
				<a id='home-button'><</a>
				<a id='contact-button'>contact</a>
				<a id='blog-button'>blog</a>
			</div>
		</header>
		<div id='front'>
			<h1>HI, I'M MARCELO</h1>
			<div id='contact-menu'>
				<li>
					<a href='marcelovicentegc@gmail.com'><i class="fas fa-envelope"></i></a>
					<a href='https://github.com/marcelovicentegc' target='_blank'><i class='fab fa-github'></i></a>
					<a href='https://www.linkedin.com/in/marcelo-cardoso-b77261144/' target='_blank'><i class='fab fa-linkedin-in'></i></a>
					<a href='https://www.strava.com/athletes/35289893' target='_blank'><i class='fab fa-strava'></i></a>
				</li>
			</div>
		</div>
		<div id='pegafrito'>
		</div>
	</div>
    <script src="{% static 'index/js/globe.js' %}"></script>
</body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
    <title>Language settings | Marcelo Cardoso</title>
    <meta charset="utf8" />
    <meta name="viewport" content="width = device-width, initial-scale = 1">
	<link rel='shortcut icon' type='image/png' href='/static/home/img/m.jpg' sizes='32x32'/>
    <link rel='stylesheet' href="{% static 'home/css/main.css'%}" type="text/css" />
	<script src='https://code.jquery.com/jquery-3.3.1.min.js' integrity='sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=' crossorigin='anonymous'></script>
	<script src="{% static 'home/js/home.js' %}"></script>
	{% include "universal/google.html" %}
</head>
<body>
	<p><a class='button' id='en'>en </a><a class='separator'>|<a class='button' id='pt'> pt</a></p>
</body>
</html>

home/templates/universal/google.html
{% block content %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-128443240-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-128443240-1');
    </script>
{% endblock %}

ptbr/templates/ptbrblog/newsfeed.html
<!DOCTYPE html>
<html lang='eng'>
<head>
    {% load static %}
    <title> Passagens | Marcelo Cardoso </title>
    <meta charset='utf8'/>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='shortcut icon' type='image/png' href='/static/home/img/m.jpg' sizes='32x32'/>
    <link rel='stylesheet' type='text/css' href="{% static 'blog/css/main.css'%}"/>
    <script src='https://code.jquery.com/jquery-3.3.1.min.js' integrity='sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=' crossorigin='anonymous'></script>
    <script id="dsq-count-scr" src="//marcelo-page.disqus.com/count.js" async></script>
    <script src="{% static 'blog/js/newsFeedPt.js' %}"></script>    
    {% include "universal/google.html" %}
    <script>
        {% for topic in topic_list %}
        $(document).ready(function() {
            $('#publication-container-{{topic.name}}').click(function() {
                var publicationContained = $('#publication-contained-{{topic.name}}');
                if (publicationContained.css('display') == 'block') {
                    $.fn.closePublicationContained(publicationContained);
                    if (publicationContained.next().is('li')) {
                        setTimeout(function() {
                            publicationContained.next().animate({
                                'margin-top': '0'
                                });
                        }, 200);
                    }
                    else {

                    }
                } else if (publicationContained.css('display') == 'none') {
                    $.fn.openPublicationContained(publicationContained);
                    if (publicationContained.next().is('li')) {
                      publicationContained.next().animate({
                        'margin-top': publicationContained.outerHeight() + 30
                        });
                    }
                    else {

                    }
                } else {
                    
                }
            });
        });
        {% endfor %}
    </script>
</head>

<body id='top'>    
    <div id='toggle-sidebar-wrapper'>
        <div id='toggle-wrapper'>
            <div id='toggle-container'>
                <a class='button' id='toggle-button' aria-hidden='true'>+</a>
            </div>
        </div>
        <div id='sidebar-wrapper'>
            <ul>
                <div id='remote-controller-wrapper'>
                    <li>
                        <a class='close-sidebar-button button' id='index-button'>m</a>
                        <a class='close-sidebar-button button'>-</a>
                        <a href='#top' class='close-sidebar-button button scroll'>top</a>
                    </li>
                </div>
                {% for topic in topic_list %}
                <li class='publication-container' id='publication-container-{{topic.name}}'><a class='button topic-name'>{{topic.name}}</a></li>
                    <div class='publication-contained' id='publication-contained-{{topic.name}}' style='position: asbsolute;
                                                                                                        background-color: #fff;
                                                                                                        box-shadow: -2px 2px 4px 2px #9b9b9b71 !important;
                                                                                                        display: none;
                                                                                                        margin-top: 10px;
                                                                                                        margin-left: 25px;
                                                                                                        margin-bottom: 20px;'>
                    {% for post in topic.postmodel_set.all %}
                    <li><a href='#{{post.id}}' class='close-sidebar-button-post scroll' class='post-title'>{{post.title}}</a></li>
                    {% endfor %}
                </div>
                {% endfor %}
            </ul>
        </div>
    </div>
    <header>
        <div id='blog-title-wrapper'>
            <h1 id='blog-title'>Passagens</h1>
        </div>
    </header>
    
    <div id='essay-wrapper'>
        <div class='mona-lisa'>
            <img src = "{{ artwork.image.url }}" title='{{ artwork.title }}'>
        </div>
        {% for post in post_list %}
        <div class='essay-header'>
            <h2 class='essay-title'><a href='/pt-br/blog/{{post.slug}}' name='published-essay' id='{{post.id}}'>{{post.title}}</a></h2>
            <div class='essay-date'>
                {{ post.date|date:"M d, Y" }}
                <div class ='disqus-comment-count' data-disqus-identifier='{{post.id}}'>
                </div>
            </div>
        </div>
        <div class='essay'>{{ post.body|safe|linebreaks }}</div>
        <div class='mona-lisa'>
            {% if post.image.url != None %}
            <a><img src="{{ post.image.url }}"></a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</body>
</html>

ptbr/templates/ptbrblog/post.html
<!DOCTYPE html>
<html lang='eng'>
<head>
    {% load static %}
    <title> {{object.title}} | Marcelo Cardoso </title>
    <meta charset='utf8'/>
	<meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' href="{% static 'blog/css/main_post.css'%}"/>
    <link rel='shortcut icon' type='image/png' href='/static/home/img/m.jpg' sizes='32x32'/>
    <script src='https://code.jquery.com/jquery-3.3.1.min.js' integrity='sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=' crossorigin='anonymous'></script>
    <script id="dsq-count-scr" src="//marcelo-page.disqus.com/count.js" async></script>
    <script src="{% static 'blog/js/post.js' %}"></script>
    {% include "universal/google.html" %}
</head>

<body id='top'>    
    <div id='toggle-sidebar-wrapper'>
        <div id='toggle-wrapper'>
            <div id='toggle-container'>
                <a class='button' id='blog-button' aria-hidden='true'><</a>
            </div>
        </div>
    </div>

    <div id='essay-wrapper'>
        <div id='essay-header'>
            <h2 class='essay-title'><a name='published-essay' id='{{object.id}}'>{{object.title}}</a></h2>
            <div class='essay-date'>
                {{ object.date|date:"M d, Y" }}
            </div>
        </div>
        <div class='essay'>{{ object.body|safe|linebreaks }}</div>
        <div class='mona-lisa'>
        {% if object.image.url != None %}
            <a><img src="{{ object.image.url }}"></a>
        {% endif %}
        </div>
        <div id='disqus_thread'></div>
        <script src="{% static 'blog/js/disqusPt.js' %}"></script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </div>
</body>
</html>

ptbr/templates/ptbrindex/index.html
<!DOCTYPE html>
<html lang='eng'>
<head>
	{% load static %}
    <title> Marcelo Cardoso </title>
    <meta charset="utf8" />
    <meta name="viewport" content="width = device-width, initial-scale = 1">
	<link rel='shortcut icon' type='image/png' href='/static/home/img/m.jpg' sizes='32x32'/>
	<link rel='stylesheet' href="{% static 'index/css/main.css' %}" type='text/css'/>
	<link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.4.1/css/all.css' integrity='sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz' crossorigin='anonymous'>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/97/three.js'></script>
	<script src='https://code.jquery.com/jquery-3.3.1.min.js' integrity='sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=' crossorigin='anonymous'></script>
    <script src="{% static 'index/js/index.js' %}"></script>
	<script src="{% static 'index/js/indexPt.js' %}"></script>
	{% include "universal/google.html" %}
</head>
<body>
	<div id='wrapper'>
		<header>
			<div id='menu'>
				<a id='home-button'><</a>
				<a id='contact-button'>contato</a>
				<a id='blog-button'>blog</a>
			</div>
		</header>
		<div id='front'>
			<h1>OLÁ, EU SOU O MARCELO</h1>
			<div id='contact-menu'>
				<li>
					<a href='marcelovicentegc@gmail.com'><i class="fas fa-envelope"></i></a>
					<a href='https://github.com/marcelovicentegc' target='_blank'><i class='fab fa-github'></i></a>
					<a href='https://www.linkedin.com/in/marcelo-cardoso-b77261144/' target='_blank'><i class='fab fa-linkedin-in'></i></a>
					<a href='https://www.strava.com/athletes/35289893' target='_blank'><i class='fab fa-strava'></i></a>
				</li>
			</div>
		</div>
		<div id='pegafrito'>
		</div>
	</div>
	<script src="{% static 'index/js/globe.js' %}"></script>
</body>
</html>